### ISSUE TITLE
Unable to npm install due to klasa package

### ISSUE THREAD

**Issue by BrettMerri** [gc/oldschoolbot#214]
Hi guys, this is my first time cloning this repo. When I run `npm install` I get the error:
```bash
pathspec '916/head' did not match any file(s) known to git
```

I looked at the NPM logs and apparently it's due to the [klasa package](https://github.com/dirigeants/klasa).

In our `package.json`, there is this:

```
"klasa": "github:dirigeants/klasa#916/head",
```

I am not familiar with this syntax. Is this trying to install the package from a specific branch in Klasa (916/head)? Did the branch get deleted on Klasa's end because I don't see it in in their [list of branches](https://github.com/dirigeants/klasa/branches/all)?

When I delete `klasa` from `package.json` and run `npm install`, it works just fine.

Is anyone else having this issue? Here is what I am running this with:
- windows 10
- node v12.16.2
- npm  v6.14.4
- git 2.26.0.windows.1

**Comment by gc** [comment]
Try using `yarn`

**Comment by BrettMerri** [comment]
Cool, so yarn works. Thank you.

I tried `npm install` on my macbook as well and it did not work either due to the same error. Should we update the docs to use `yarn` instead of `npm` for this project?

**Comment by gc** [comment]
The installations instructions are completely out of date, as nobody has updated them yet (I've literally been just way too busy). If you're intending on setting up the bot you should ask for help in the #developers channel, as theres a few things to know/do

**Comment by BrettMerri** [comment]
Resolved with using yarn instead of npm. #215
