### ISSUE TITLE
Please Explain The Usefulness of Skills

### ISSUE THREAD

**Issue by BrandonEnglish848** [gc/oldschoolbot#269]
You have so many functions and awesome skill menus, but to my knowledge of the way the bot works, it doesn't factor any skill levels into bossing runs or questing requirements / completion times. Is there something that is going to be implemented to integrate skills, or is skill leveling just there to flex max capes?

**Comment by gc** [comment]
This is a question you should ask in the discord server: http://discord.gg/ob
