### ISSUE TITLE
allow +price to accept multiple items

### ISSUE THREAD

**Issue by GoodBlokeAri** [gc/oldschoolbot#5]
parse multiple items separated by comma to be price checked

**Comment by gc** [comment]
How do you suggest multiple are formatted into one message? Its not super hard to just type out the command again

**Comment by GoodBlokeAri** [comment]
Similarly to how +diary formats them maybe? It was just a suggestion.
Possible pad the format for each item to be in smaller, cubes and possibly include an image of the item too.
![untitled-1](https://user-images.githubusercontent.com/5451883/42605448-9aad3634-853d-11e8-9575-f8638263cb6b.png)
