### ISSUE TITLE
Add Command to Enable/Disable Aliases

### ISSUE THREAD

**Issue by nburbine** [gc/oldschoolbot#51]
Add command to enable/disable individual aliases of a command.
I started adding this at #52

- Currently `+cmd disable w` disables usage of `+w` and `+wiki`

- Proposed `+alias disable w` disables usage of `+w` but not `+wiki`

**Comment by gc** [comment]
Hey! Sorry for the delay. May I ask whats the use case/purpose of disabling `+w`? The alias is there to make it faster/easier to type.

**Comment by gc** [comment]
Closing due to lack of response and the PR being closed too.
