### ISSUE TITLE
+clues displays incorrect information

### ISSUE THREAD

**Issue by 000000653** [gc/oldschoolbot#56]
Beginner clues were added and LMS's score changed position on the hiscores, breaking this feature.

What's being displayed
![Discord_yJ57U1e05C](https://user-images.githubusercontent.com/40111569/57128568-742af500-6d59-11e9-87b0-e34395a1d1fe.png) 

What's expected to be displayed
![chrome_gWHCgcAUGA](https://user-images.githubusercontent.com/40111569/57128702-e1d72100-6d59-11e9-8a6f-2f56058ed0be.png)

**Comment by gc** [comment]
Should be fixed now. Thanks for reporting this, I appreciate it.
