### ISSUE TITLE
EHP

### ISSUE THREAD

**Issue by permedd** [gc/oldschoolbot#61]
![image](https://user-images.githubusercontent.com/37475765/59376138-749ab080-8d47-11e9-9f72-6e2ea5174945.png)

can you add total EHP on +stats, i know there is a +ehp command but can you add it on +stats as well.
also when doing +gains xp levels day/week/month/year can it also show how much ehp we have gained on it as well, please

**Comment by gc** [comment]
With the current state of the CML api (being completely unstable) this is definitely not possible to do atm. Also I'm not sure it makes sense to go there in the first place. Willing to re-open if CML improves.
