### ISSUE TITLE
+xpto99 uses total xp rather than clamped xp

### ISSUE THREAD

**Issue by Error64** [gc/oldschoolbot#8]
When using the xp to 99 command it doesn't use the clamped xp as it should. Here is a screenshot showing that the total xp for 99 exactly has been reached but it's just because some skills have way over 13m.

![image](https://user-images.githubusercontent.com/39537670/45257230-09304680-b3a3-11e8-851b-a435a6dfa78d.png)

**Comment by gc** [comment]
If I understand you correctly, the bug is that the Total XP remaining to 99 in all skills says 0, but it shouldnt be 0? Should be fixed.
